name: Build LaTeX diff document
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      PAPER: "main"
      MAIN: ${{ github.event.pull_request.base.sha }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile LaTeX diff
        id: compileLaTeXdiff
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ env.PAPER }}-diff${{ env.MAIN }}.tex
          working_directory: tex
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace && latexdiff-vc --git --flatten --disable-auto-mbox --exclude-safecmd="Cref,Cref\*,hspace" -r ${{ env.MAIN }} ${{ env.PAPER }}.tex
        continue-on-error: true
      - name: Upload PDF
        if: steps.compileLaTeXdiff.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: Success--Here-is-the-Diff-PDF
          path: |
            tex/${{ env.PAPER }}-diff${{ env.MAIN }}.pdf
      - name: Upload build logs
        if: steps.compileLaTeXdiff.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: Diff-Build-Failed--Here-are-the-Logs
          path: |
            tex/**/*.log
      - name: Fail job if build failed
        if: steps.compileLaTeXdiff.outcome == 'failure'
        run: exit 1
